### PR TITLE
VaR

### PR DESCRIPTION
**Pull request by bachirchaouiche**

### CODE REVIEW

**Comment by gusamarante** [comment]
This is a great idea. Code seems to be well structured. A few requests before accepting the code.

* The function that computes the VaR should return the VaR as an output.
* Ploting charts should be optional, just in case the user asks for it. This allows your functions to be used in loops, without charts showing up everytime.
* All of the functions should be in one file and the example application should be in another.

Keep it up

**Comment by bachirchaouiche** [comment]
Thank You Gustavo. Please see changes as requested.
`import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# load data with prices
def load_data():
    df = pd.read_excel('Dados para VaR em python.xlsx')
    return df

def calc_portfolio(df_prices,df_par):
# '''
# :param df_prices: pandas dataframe with stock prices a
# :param df_par: pandas dataframe with parameters
# '''        
    df_prices = df_prices.sort_index(ascending = True)
    df_ret = pd.DataFrame(index = df_prices.index, columns = df_prices.columns)
    df_pl= pd.DataFrame(index = df_prices.index,columns = df_prices.columns)
    for stock in df_prices:     
        ret_series = df_prices[stock].pct_change()
        profit_loss_serie = ret_series*df_par[stock].POSITION
        df_ret[stock] = pd.DataFrame(ret_series)
        df_pl[stock] = pd.DataFrame(profit_loss_serie)
    return df_ret.dropna(),df_pl.dropna()    
    
def calculate_var(df_pl, confidence=0.01, print_result = False):
    
    df_pl['PORTFOLIO_VALUE'] = df_pl.sum(axis=1)
    port_rets = df_pl['PORTFOLIO_VALUE']
    port_rets = port_rets.sort_values(axis=0, ascending=True)
    var =  np.percentile(port_rets, confidence)

    if(print_result == True):
        # RETURN HISTOGRAM
        plt.figure(figsize = (10,6))
        plt.hist(port_rets,density=True, alpha = 0.6,  histtype='bar', rwidth=0.8, facecolor="b")
        plt.xlabel('Portfolio Returns')
        plt.ylabel('Frequency')
        plt.title(r'Histogram of Stock Portfolio Returns', fontsize=18, fontweight='bold')
        plt.show() 
        print ("99.99% VaR: " , "R$ {0:.2f}".format(round(var, 2)))
        
    return var`

**Comment by gusamarante** [comment]
I can not see the changes in the you version of the repository. Did you update it?

**Comment by gustavobsoares** [comment]
This has been open too long. I'm closing it.

**Comment by gustavobsoares** [comment]
This has been open too long. I'm closing it.

**Pull request closed without merging**
