### PR TITLE
Create_Bacen_IF_Data

### PR DESCRIPTION
**Pull request by renanamp**
# Financas Quantitativas
# Contribuição ao Finance Hub: Rentabilidade dos bancos
# Autores: Ivan Zemella e Renan Pereira

### CODE REVIEW

**Comment by renanamp** [comment]
# Financas Quantitativas
# Contribuição ao Finance Hub: Rentabilidade dos bancos
# Autores: Ivan Zemella e Renan Pereira

**Comment by renanamp** [comment]
# Financas Quantitativas
# Contribuição ao Finance Hub: Rentabilidade dos bancos
# Autores: Ivan Zemella e Renan Pereira

**Comment by gusamarante** [comment]
There is a great potential here. I did not know about this data source from the brazilian central bank. Is there a website that describes the data that is available here?

There are still a few points to correct:
* The code is very poluted. In python, counting variables do not need to be reset to zero, tab spaces are relevant for the code and some of them are not well aligned.
* You are using the `requests` library to get a json file from the web and then reading it element by element. You can you use [`panda.read_json`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_json.html) method. This will probably save more than 100 lines of code.
* I can see that there is some structure to the URL you need to read the files and that there is a lot more than just ROEs that you can get. You can turn this webscrapping routine into a python class. This will make much easier for it to be reused by other people in the future. Remember that a contribution is a functionality, not an analysis.

**This looks like a great contribuion. Keep it up!**

**Comment by renanamp** [comment]
[Bacen_IF_Data_v2.zip](https://github.com/Finance-Hub/FinanceHub/files/3365146/Bacen_IF_Data_v2.zip)

**Comment by gusamarante** [comment]
You guys deleted the old file and uploaded a zip. You have to make the modifications on your fork of the project and then "commit and push" the changes on the py files, otherwise we cannot properly see the changes made to the repository.

**Comment by renanamp** [comment]
# Quantitative Finance
# Insper
# Authors: Ivan Zemella and Renan Pereira

# Imports BancoCentral class
from classes.BancoCentral import BancoCentral

# Imports Pandas class
import pandas as pd

escolha = input('Do you want to enter periods manually? Y / N ')

# Converts the choice to uppercase
escolha = escolha.upper()

# Create an object of the Central Bank class
bancoCentral = BancoCentral()

# Automatic Download
if(escolha == 'N'):
	
	i = 0
	
	listaTrimestres = bancoCentral.trimestres
	
	for contador in range(0, len(listaTrimestres)):
		
		trimestre = listaTrimestres[contador]
		
		bancoCentral.obterTrimestre(trimestre)
		
		i += 1

# Manually Download
elif(escolha == 'Y'):
	
	continuar = True
	
	while(continuar):
		
		trimestre = input('Choose the quarter?  ')
		trimestre = trimestre.upper()
		
		bancoCentral.obterTrimestre(trimestre)
		
		deseja_continuar = input('Do you wish to continue? [Y / N]       ')
		
		if(deseja_continuar.upper() == 'N'):
			continuar = False

resultado = bancoCentral.obterResultado()

print(resultado)

df = pd.DataFrame.from_dict(resultado,orient='index')
df.to_excel(r"df_banks.xlsx")

print('FILE EXPORTED SUCCESSFULLY!')

print('END')

**Pull request closed without merging**
